const categories = [
  {id:'mustdo', icon:'⭐', title:'My Must-Do List', note:'Your personal cruise shortlist'},
  {id:'shows', icon:'🎭', title:'Shows', note:'Productions & show venues'},
  {id:'dining', icon:'🍴', title:'Eat & Drink', note:'Restaurants, cafes & bars'},
  {id:'pools', icon:'🏊', title:'Pools & Relaxation', note:'Pools, water & chill zones'},
  {id:'activities', icon:'🎢', title:'Activities', note:'Waterpark & attractions'},
  {id:'services', icon:'⚓', title:'Ship Services', note:'Guest Services & essentials'}
];

const destinations = [
  {id:'basecamp', name:'Basecamp', deck:'16', area:'Aft · Thrill Island', category:'dining', mustdo:true, icon:'🍔', keywords:'base camp basecamp burger hot dog thrill island', route:['Leave Cabin 7456 and head to a main elevator/stair core.','Go up to Deck 16.','Follow signs aft for Thrill Island.','Look for Basecamp near the Thrill Island attractions.'], note:'Your saved recommendation. Basecamp is on Deck 16 in Thrill Island.', confidence:'VENUE + DECK VERIFIED; CABIN-TO-CORE TURN DETAILS IN PROGRESS'},
  {id:'aquadome', name:'AquaDome / AquaTheater', deck:'14–15', area:'Forward · AquaDome', category:'shows', mustdo:true, icon:'🌊', keywords:'aquadome aquatheater dome torque pirates mermaids', route:['Leave Cabin 7456 and reach a main elevator/stair core.','Go up to Deck 15.','Follow signs forward for AquaDome.','AquaTheater is inside the AquaDome neighborhood.'], note:'Your saved recommendation. AquaDome occupies the forward area of Decks 14–15; AquaTheater is the show venue.', confidence:'VENUE LOCATION VERIFIED; CABIN-TO-CORE TURN DETAILS IN PROGRESS'},
  {id:'backfuture', name:'Back to the Future: The Musical', deck:'3–5', area:'Forward · Royal Theater', category:'shows', mustdo:true, icon:'🚗', keywords:'back future musical broadway royal theater show', route:['From Cabin 7456, reach a main elevator/stair core.','Go down to the Royal Theater level; Deck 4 is a useful theater access level.','Follow signs forward for Royal Theater.','Arrive early and use the Royal app for your sailing’s performance time/reservation.'], note:'Royal Caribbean lists Back to the Future: The Musical on Star of the Seas. Royal Theater spans the forward lower decks.', confidence:'SHOW + VENUE VERIFIED; PERFORMANCE TIME COMES FROM YOUR SAILING'},
  {id:'torque', name:'Torque', deck:'14–15', area:'Forward · AquaTheater', category:'shows', mustdo:true, icon:'🤸', keywords:'torque aqua show aquatheater diving', route:['From Cabin 7456, use a main elevator/stair core to Deck 15.','Follow signs forward into AquaDome.','Continue to AquaTheater.','Use the Royal app for your sailing’s show time/reservation.'], note:'Torque is Royal Caribbean’s high-energy AquaTheater production on Star of the Seas.', confidence:'SHOW + VENUE VERIFIED; PERFORMANCE TIME COMES FROM YOUR SAILING'},
  {id:'sol', name:'SOL', deck:'4–5', area:'Absolute Zero · Ice arena', category:'shows', mustdo:true, icon:'⛸️', keywords:'sol ice show absolute zero skating', route:['From Cabin 7456, reach a main elevator/stair core.','Go down to Deck 5 for Absolute Zero access.','Follow signs for Absolute Zero.','Use the Royal app for your sailing’s performance time/reservation.'], note:'SOL is one of the entertainment productions Royal Caribbean lists for Star of the Seas.', confidence:'SHOW + VENUE VERIFIED; PERFORMANCE TIME COMES FROM YOUR SAILING'},
  {id:'windjammer', name:'Windjammer Marketplace', deck:'15', area:'Aft · Dining', category:'dining', icon:'🥐', keywords:'buffet breakfast lunch dinner aft', route:['Leave Cabin 7456 and head toward a main elevator/stair core.','Take the elevator to Deck 15.','On Deck 15, follow signs toward the aft dining area and Windjammer Marketplace.'], note:'Windjammer is on the aft portion of Deck 15.', confidence:'VENUE LOCATION VERIFIED; CORRIDOR ROUTE CONSERVATIVE'},
  {id:'mdr', name:'Main Dining Room', deck:'3–5', area:'Aft · Dining', category:'dining', icon:'🍽️', keywords:'main dining dinner breakfast lunch', route:['Leave Cabin 7456 and reach a main elevator/stair core.','Go down to Deck 5 for the upper level of the three-story Main Dining Room.','Follow signs aft toward the Dining Room entrance.'], note:'The Main Dining Room occupies the aft area across Decks 3–5.', confidence:'VENUE LOCATION VERIFIED; CORRIDOR ROUTE CONSERVATIVE'},
  {id:'theater', name:'Royal Theater', deck:'3–5', area:'Forward · Entertainment', category:'shows', icon:'🎭', keywords:'show theater performance broadway', route:['From Cabin 7456, head to a main elevator/stair core.','Go down to the Royal Theater levels.','Follow Royal Theater signs toward the forward entertainment area.'], note:'Royal Theater is the home of major stage productions including Back to the Future.', confidence:'VENUE AREA VERIFIED; EXACT CABIN-TO-CORE ROUTE TO BE REFINED'},
  {id:'absolute', name:'Absolute Zero', deck:'4–5', area:'Entertainment · Ice arena', category:'shows', icon:'🧊', keywords:'ice skating ice show laser tag sol', route:['From Cabin 7456, reach a main elevator/stair core.','Go to Deck 5 for the upper part of Absolute Zero.','Follow signs to Absolute Zero; the arena spans two levels.'], note:'Absolute Zero spans the Deck 4–5 area.', confidence:'VENUE AREA VERIFIED; EXACT ENTRANCE TO BE REFINED'},
  {id:'promenade', name:'Royal Promenade', deck:'5–6', area:'Midship · Shopping & Dining', category:'dining', icon:'🛍️', keywords:'royal promenade shops sorrentos pearl cafe', route:['From Cabin 7456, head toward a main public-area core.','Use the elevator/stairs to Deck 5 or 6.','Follow signs into the Royal Promenade.'], note:'The Royal Promenade is the ship’s central indoor public neighborhood on Decks 5–6.', confidence:'NEIGHBORHOOD LOCATION VERIFIED; ROUTE CONSERVATIVE'},
  {id:'centralpark', name:'Central Park', deck:'8', area:'Midship · Neighborhood', category:'dining', icon:'🌳', keywords:'central park chops park cafe izumi', route:['From Cabin 7456, head toward a main public-area core.','Go to Deck 8.','Follow signs for Central Park.'], note:'Central Park occupies Deck 8.', confidence:'NEIGHBORHOOD LOCATION VERIFIED; ROUTE CONSERVATIVE'},
  {id:'category6', name:'Category 6 Waterpark', deck:'16 & 20', area:'Aft · Thrill Island', category:'activities', icon:'🎢', keywords:'waterpark slides category 6 thrill island', route:['From Cabin 7456, use the elevators to Deck 16.','Follow signs aft for Thrill Island / Category 6.','Some slide entry structures are on higher decks; follow the specific attraction signage.'], note:'Category 6 is in Thrill Island on the upper decks.', confidence:'ATTRACTION LOCATION VERIFIED; ROUTE CONSERVATIVE'},
  {id:'royalbay', name:'Royal Bay Pool', deck:'15', area:'Midship · Chill Island', category:'pools', icon:'🏖️', keywords:'royal bay pool swim tonic chill island', route:['From Cabin 7456, take a main elevator/stair core to Deck 15.','Follow signs toward Chill Island / Royal Bay Pool.'], note:'Royal Bay Pool is on Deck 15.', confidence:'POOL LOCATION VERIFIED; ROUTE CONSERVATIVE'},
  {id:'guestservices', name:'Guest Services', deck:'5', area:'Midship · Services', category:'services', icon:'🧑‍💼', keywords:'guest services reception help desk', route:['From Cabin 7456, reach a main elevator/stair core.','Go to Deck 5.','Follow signs for Guest Services.'], note:'Guest Services is on Deck 5.', confidence:'SERVICE LOCATION VERIFIED; ROUTE CONSERVATIVE'}
];

const unavailableRecommendations=[{name:'Johnny Rockets', icon:'🍔', text:'Important catch: current Star of the Seas venue lists do not show Johnny Rockets. Icon-class ships use Surfside dining instead. I left this visible as a recommendation to verify rather than routing you to a venue that does not appear to be onboard.'}];

const deckInfo = [
  {deck:'3–5', title:'Main Entertainment + Dining', text:'Royal Theater is forward, Main Dining Room is aft, and Absolute Zero occupies the lower entertainment decks.'},
  {deck:'5–6', title:'Royal Promenade', text:'The central indoor public neighborhood: food, bars, shops and major circulation.'},
  {deck:'7', title:'Your Home', text:'Cabin 7456 is your home base on Deck 7. We are refining its exact path to the closest useful elevator core.'},
  {deck:'8', title:'Central Park', text:'Outdoor garden neighborhood with restaurants and bars.'},
  {deck:'14–15', title:'AquaDome', text:'Forward end of the ship. AquaDome combines entertainment, dining and relaxation under the dome.'},
  {deck:'15', title:'Pools + Windjammer', text:'Royal Bay Pool, Chill Island, Windjammer and AquaDome access are major Deck 15 landmarks.'},
  {deck:'16+', title:'Thrill Island', text:'Basecamp, Category 6 and other high-energy attractions are concentrated on the upper aft decks.'}
];

let currentView='home'; let lessonIndex=0;
const lessons=[
  {q:'You want Basecamp. Which deck should you remember?', a:['Deck 6','Deck 8','Deck 16'], correct:2, why:'Basecamp is on Deck 16 in Thrill Island.'},
  {q:'Which end of the ship should you associate with AquaDome?', a:['Forward','Midship','Aft'], correct:0, why:'AquaDome is a major forward landmark on Decks 14–15.'},
  {q:'Where should you head for Back to the Future: The Musical?', a:['AquaTheater','Royal Theater','Absolute Zero'], correct:1, why:'Back to the Future is staged in the Royal Theater.'}
];

function el(id){return document.getElementById(id)}
function renderCategories(){el('categoryGrid').innerHTML=categories.map(c=>`<button class="cat" data-cat="${c.id}"><strong>${c.icon} ${c.title}</strong><span>${c.note}</span></button>`).join('')}
function row(d){return `<button class="dest-row" data-dest="${d.id}"><span class="dest-icon">${d.icon}</span><span class="dest-main"><span class="dest-name">${d.name}${d.mustdo?' <b class="must-pill">MUST-DO</b>':''}</span><span class="dest-meta">Deck ${d.deck} · ${d.area}</span></span><span class="dest-arrow">›</span></button>`}
function renderSearch(list, extra=''){el('destinationList').innerHTML=list.map(row).join('')+extra; el('destinationList').classList.toggle('hidden',list.length===0&&!extra)}
function navigate(view){currentView=view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));el(view+'View').classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
function showRoute(id){const d=destinations.find(x=>x.id===id);if(!d)return;el('routeContent').innerHTML=`<div class="route-hero"><div class="eyebrow">FROM CABIN 7456</div><h2>→ ${d.name}</h2><div class="route-tag">Deck ${d.deck} · ${d.area}</div></div><div class="route-card"><div class="confidence">${d.confidence}</div>${d.route.map((s,i)=>`<div class="route-step"><div class="step-num">${i+1}</div><div class="step-text">${s}</div></div>`).join('')}</div><div class="route-card"><h3>🧭 Destination note</h3><div class="callout">${d.note}</div></div><button class="home-action" onclick="navigate('home')">⌂ Back to Navigator</button>`;navigate('route')}
function renderDecks(){el('deckCards').innerHTML=deckInfo.map(x=>`<div class="deck-card"><div class="deck-label">DECK ${x.deck}</div><h3>${x.title}</h3><p>${x.text}</p></div>`).join('')}
function renderLesson(){const l=lessons[lessonIndex];el('lessonCard').innerHTML=`<div class="confidence">CHALLENGE ${lessonIndex+1} OF ${lessons.length}</div><div class="lesson-q">${l.q}</div><div class="answers">${l.a.map((x,i)=>`<button class="answer" data-answer="${i}">${x}</button>`).join('')}</div><div id="lessonFeedback" class="lesson-feedback"></div>`;el('lessonCard').querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>{const chosen=Number(b.dataset.answer),all=el('lessonCard').querySelectorAll('.answer');all.forEach(a=>a.disabled=true);b.classList.add(chosen===l.correct?'correct':'wrong');if(chosen!==l.correct)all[l.correct].classList.add('correct');el('lessonFeedback').innerHTML=(chosen===l.correct?'✅ Correct. ':'Not quite. ')+l.why+(lessonIndex<lessons.length-1?' <button id="nextLesson" class="answer next">Next challenge →</button>':' <button id="finishLesson" class="answer next">Back to navigator</button>');if(el('nextLesson'))el('nextLesson').onclick=()=>{lessonIndex++;renderLesson()};if(el('finishLesson'))el('finishLesson').onclick=()=>navigate('home')}))}
function showMustDo(){const extra=unavailableRecommendations.map(x=>`<div class="unavailable"><strong>${x.icon} ${x.name} · CHECK</strong><span>${x.text}</span></div>`).join('');renderSearch(destinations.filter(d=>d.mustdo),extra)}
renderCategories();renderSearch([]);renderDecks();renderLesson();
document.addEventListener('click',e=>{const cat=e.target.closest('[data-cat]');if(cat){if(cat.dataset.cat==='mustdo')showMustDo();else renderSearch(destinations.filter(d=>d.category===cat.dataset.cat));el('searchInput').value='';return}const dest=e.target.closest('[data-dest]');if(dest){showRoute(dest.dataset.dest);return}const view=e.target.closest('[data-view]');if(view){navigate(view.dataset.view);return}const go=e.target.closest('[data-go]');if(go){navigate(go.dataset.go);return}});
el('searchInput').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();if(!q){renderSearch([]);return}renderSearch(destinations.filter(d=>(d.name+' '+d.area+' '+d.keywords).toLowerCase().includes(q)))});
el('takeHome').addEventListener('click',()=>{el('routeContent').innerHTML=`<div class="route-hero"><div class="eyebrow">HOME BASE</div><h2>→ Cabin 7456</h2><div class="route-tag">Deck 7</div></div><div class="route-card"><h3>When you're ready to head home</h3><div class="route-step"><div class="step-num">1</div><div class="step-text">Find your nearest main elevator or stair core and navigate to Deck 7.</div></div><div class="route-step"><div class="step-num">2</div><div class="step-text">Use Deck 7 cabin-number signs to work toward Cabin 7456.</div></div><div class="callout">Next routing milestone: choose your current venue and get a venue → Cabin 7456 route.</div></div><button class="home-action" onclick="navigate('home')">⌂ Back to Navigator</button>`;navigate('route')});
el('infoBtn').onclick=()=>navigate('info');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
